---
title: "Taller 4"
author: "Nathalie Bareño, Karen Vargas y Sebastián Rincón"
output: html_notebook
date: "16 de mayo"
---

```{r}
library(tidyverse)
library(readxl)
```

# Cargar Bases de datos

```{r}
NorMen <- read_excel("datos/iabbd_8010_v1 (2).xls", 
                            sheet = "NOR-Men")

NorWom <- read_excel("datos/iabbd_8010_v1 (2).xls",
                     sheet = "NOR-Women")

USMen <- read_excel("datos/iabbd_8010_v1 (2).xls",
                     sheet = "USA-Men")

USWom <- read_excel("datos/iabbd_8010_v1 (2).xls",
                     sheet = "USA-Women")
HDI <- read_csv("datos/Human Development Index (HDI) (1).csv", 
                  skip = 5)

CPI <- read_delim("datos/data_csv.csv", delim = ",")

Unem <- read_excel("datos/API_SL.UEM.TOTL.ZS_DS2_es_excel_v2_2253098.xls",
                   sheet = "Data")

```

# Modificando bases de datos

```{r}
# Indice de percpeción de corrupción 
CPI <- CPI %>% select(c("Jurisdiction", "2010"))

CPI <- rename(CPI, Country = "Jurisdiction", Corruption = "2010")

# Indice de Desarrollo  Humano

HDI <- HDI %>% select(c("Country", "2010"))

HDI <- rename(HDI, Development = "2010")

# Desempleo

Unem <- Unem %>% select(c("Data Source", "...55"))

Unem <- rename(Unem, Country = "Data Source", Unemployment = "...55")

Unem <- Unem[-c(1,2,3),]

# Noruega Hombres

NorMen <- NorMen %>% select(c("Norway", "...29"))

NorMen <- rename(NorMen, Country = "Norway", HighMenNor = "...29")

NorMen <-  NorMen[-c(1,2,3),]

# Noruega Mujeres 

NorWom <- NorWom %>% select(c("Norway", "...29"))

NorWom <- rename(NorWom, Country = "Norway", HighWomNor = "...29")

NorWom <-  NorWom[-c(1,2,3),]

# Estados Unidos Hombres

USMen <- USMen %>% select(c("United States", "...29"))

USMen <- rename(USMen, Country = "United States", HighMenUS = "...29")

USMen <-  USMen[-c(1,2,3),]

# Estados Unidos Mujeres

USWom <- USWom %>% select(c("United States", "...29"))

USWom <- rename(USWom, Country = "United States", HighWomUS = "...29")

USWom <-  USWom[-c(1,2,3),]

```

# Unir

```{r}

Union1 <- left_join(NorMen,NorWom, by = "Country") 

Union2 <- left_join(USWom, USMen, by ="Country")

UnionY <- left_join(Union1, Union2, by = "Country")

Union3 <- left_join(CPI, HDI, by = "Country")

UnionX <- left_join(Union3, Unem, by = "Country")

Base <- left_join(UnionY, UnionX, by = "Country")
```



